[package]
name = "lazyadmin-adapter-project"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
lazyadmin-core = { path = "../lazyadmin-core" }
thiserror.workspace = true
tracing.workspace = true
walkdir = "2"
serde_json.workspace = true
